In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3,10)) #range takes only int not float 

[3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(2.3,20.5)

array([ 2.3,  3.3,  4.3,  5.3,  6.3,  7.3,  8.3,  9.3, 10.3, 11.3, 12.3,
       13.3, 14.3, 15.3, 16.3, 17.3, 18.3, 19.3, 20.3])

In [7]:
np.arange(5,-4,-1) #-1 is jump

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [8]:
np.arange(2,6)

array([2, 3, 4, 5])

In [10]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [12]:
np.logspace(1,5,6) #1 to 5 is divided in 6 

array([1.00000000e+01, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04, 1.00000000e+05])

In [ ]:
np.z

In [52]:
list(np.linspace(1,5,20,retstep=True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [53]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [54]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3,4,2)) #3 array of 4 by 2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [15]:
np.ones((3,4,2))+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [16]:
np.empty((2,3))

array([[1.00000000e+01, 6.30957344e+01, 3.98107171e+02],
       [2.51188643e+03, 1.58489319e+04, 1.00000000e+05]])

In [18]:
a=np.eye(4)

In [19]:
a.shape

(4, 4)

In [20]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
a.size

16

In [22]:
a.ndim

2

In [23]:
a1=np.random.randn(3,4)

In [24]:
a1

array([[ 0.96003018, -0.79933225, -0.65275822, -1.1318995 ],
       [-0.3643062 , -0.45276601,  0.53503668, -0.15851689],
       [ 1.9866529 ,  0.81887969,  1.98289202,  1.78000927]])

In [25]:
import pandas as pd

In [26]:
pd.DataFrame(a1)

0         1         2         3
0  0.960030 -0.799332 -0.652758 -1.131899
1 -0.364306 -0.452766  0.535037 -0.158517
2  1.986653  0.818880  1.982892  1.780009

In [27]:
a1

array([[ 0.96003018, -0.79933225, -0.65275822, -1.1318995 ],
       [-0.3643062 , -0.45276601,  0.53503668, -0.15851689],
       [ 1.9866529 ,  0.81887969,  1.98289202,  1.78000927]])

In [28]:
a1[1][1]

-0.45276601274528405

In [29]:
a1[0:2,0:2]

array([[ 0.96003018, -0.79933225],
       [-0.3643062 , -0.45276601]])

In [30]:
a1[[1,2],3]

array([-0.15851689,  1.78000927])

In [41]:
m1=np.random.randint(1,3,(3,3))

In [42]:
m1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [43]:
m2=np.random.randint(2,4,(3,3))

In [44]:
m2

array([[2, 3, 2],
       [2, 2, 2],
       [2, 3, 3]])

In [45]:
m1@m2 #element multiplication not matrix mult

array([[12, 16, 14],
       [10, 13, 11],
       [10, 13, 12]])

In [47]:
pow(m1,4)

array([[16, 16, 16],
       [16, 16,  1],
       [ 1, 16, 16]], dtype=int32)

In [48]:
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356]])

In [49]:
np.log10(m1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.30103]])

In [50]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ]])

array([[4, 6, 4],
       [4, 4, 2],
       [2, 6, 6]])