In [52]:
import numpy as np
import pandas as pd

In [2]:
l=[1,2,3,4,5]

In [3]:
type(l)

list

In [5]:
a=np.array(l)

In [7]:
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [9]:
a1=np.array([[1,2,3],[3,4,5]])

In [10]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
a2 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [19]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [20]:
a.ndim #one dimension one bracket

1

In [21]:
a1.ndim #two dimension two bracket

2

In [22]:
a2.ndim #three dimension three bracket

3

In [23]:
d=[1,2,3,4]

In [24]:
a=np.asarray(d)

array([1, 2, 3, 4])

In [26]:
b=np.matrix(d)

In [27]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [29]:
np.asanyarray(b) #why not array as b itself is matrix which is subclass of array

matrix([[1, 2, 3, 4]])

In [30]:
a1=a

In [31]:
a1

array([1, 2, 3, 4, 5])

In [32]:
a[0]=10

In [33]:
a

array([10,  2,  3,  4,  5])

In [34]:
a1

array([10,  2,  3,  4,  5])

In [35]:
a2=np.copy(a)

In [36]:
a2

array([10,  2,  3,  4,  5])

In [38]:
a[2]=20

In [40]:
a2[2]=30

In [41]:
a2

array([10,  2, 30,  4,  5])

In [42]:
a

array([10,  2, 20,  4,  5])

In [43]:
np.fromfunction(lambda i,j:i==j,(3,4)) #genearte dataset

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [45]:
np.random.rand(2,3) #random dataset

array([[0.4952105 , 0.82266388, 0.18173569],
       [0.08034762, 0.00297224, 0.47715368]])

In [46]:
np.random.rand(2,3,2,2)

array([[[[0.42936444, 0.24945632],
         [0.58900225, 0.99251141]],

        [[0.58126974, 0.92201608],
         [0.92738598, 0.10316287]],

        [[0.90505217, 0.32335102],
         [0.48572384, 0.58958376]]],


       [[[0.8229537 , 0.71763643],
         [0.38440189, 0.10060245]],

        [[0.25427738, 0.77666349],
         [0.55064582, 0.21805242]],

        [[0.13977288, 0.43518057],
         [0.71845261, 0.43171039]]]])

In [47]:
np.random.randn(3,3,4)

array([[[-0.38624683, -0.97394651, -1.24570522,  0.86695164],
        [ 0.94578188, -0.18742202, -0.45668079, -1.09144356],
        [ 0.07412793, -0.89909551,  1.14981418,  0.19132311]],

       [[ 0.77579168, -0.34691382, -0.84493866,  1.06448641],
        [ 0.34703975, -1.2451334 ,  0.24074651,  0.4485552 ],
        [ 0.16516962, -0.4231773 ,  0.22863465,  0.43114202]],

       [[-1.87362925,  0.49074436, -0.75934352,  1.56903582],
        [ 0.17419676, -0.05997114, -1.70438543, -0.05185445],
        [-0.10524345, -0.60298454, -0.45049122, -0.50045375]]])

In [48]:
np.random.randint(0,10,(2,2,3))

array([[[7, 8, 9],
        [4, 9, 2]],

       [[5, 3, 4],
        [7, 3, 3]]])

In [49]:
d=np.random.randint(0,10,(2,2,3))

In [53]:
pd.DataFrame(d)

ValueError: Must pass 2-d input. shape=(2, 2, 3)

In [56]:
e=d.reshape(3,4)

In [57]:
pd.DataFrame(e)

0  1  2  3
0  5  6  5  5
1  6  6  1  0
2  3  3  9  5

In [58]:
a=np.random.rand(2,3,2,2)

In [59]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(2, 3, 2, 2)

In [62]:
f=a.reshape(3,8)

In [64]:
pd.DataFrame(f) #why different data as we used random

0         1         2         3         4         5         6  \
0  0.713650  0.719286  0.491613  0.055762  0.561312  0.935836  0.142894   
1  0.283086  0.279689  0.290577  0.911595  0.811201  0.017923  0.104809   
2  0.664159  0.692477  0.157703  0.454111  0.144291  0.197967  0.219888   

          7  
0  0.496737  
1  0.529149  
2  0.227262